[build]
  publish = "build/"
  command = "npm run build"

[dev]
  publish = "build/"
  command = "npm run dev"

[[plugins]]
  # package = "./node_modules/@netlify/demo-restaurant-sites-data/plugins/{PLUGIN_DIRECTORY}"
  package = "./node_modules/@netlify/demo-restaurant-sites-data/plugins/contentful"

  [plugins.inputs]
    # Directory for the generated JSON data files to reside in
    dataDir = "src/data"